//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portrait3D.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portrait3D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect Fusion camera tracking failed. Align the camera to the last tracked position..
        /// </summary>
        internal static string CameraTrackingFailed {
            get {
                return ResourceManager.GetString("CameraTrackingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect a device first, and then restart the program!.
        /// </summary>
        internal static string ConnectDeviceFirst {
            get {
                return ResourceManager.GetString("ConnectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fps: {0:0.00}.
        /// </summary>
        internal static string Fps {
            get {
                return ResourceManager.GetString("Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect Fusion camera tracking failed in transform magnitude check..
        /// </summary>
        internal static string MagnitudeCheckFailed {
            get {
                return ResourceManager.GetString("MagnitudeCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A prerequisite component for Kinect Fusion is missing. Please refer to the Toolkit documentation for assistance..
        /// </summary>
        internal static string MissingPrerequisite {
            get {
                return ResourceManager.GetString("MissingPrerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Near mode is not supported by device.
        /// </summary>
        internal static string NearModeNotSupported {
            get {
                return ResourceManager.GetString("NearModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No DirectX11 device detected, or invalid device index - Kinect Fusion requires a DirectX11 device for GPU-based reconstruction..
        /// </summary>
        internal static string NoDirectX11CompatibleDeviceOrInvalidDeviceIndex {
            get {
                return ResourceManager.GetString("NoDirectX11CompatibleDeviceOrInvalidDeviceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No ready Kinect found!.
        /// </summary>
        internal static string NoKinectReady {
            get {
                return ResourceManager.GetString("NoKinectReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reconstruction has been reset..
        /// </summary>
        internal static string ResetReconstruction {
            get {
                return ResourceManager.GetString("ResetReconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect Fusion camera tracking failed, automatically reset volume..
        /// </summary>
        internal static string ResetVolume {
            get {
                return ResourceManager.GetString("ResetVolume", resourceCulture);
            }
        }
    }
}
