//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portrait3D.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portrait3D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le suivi de la caméra Kinect Fusion a échoué. Alignez la caméra sur la dernière position suivie.
        ///.
        /// </summary>
        internal static string CameraTrackingFailed {
            get {
                return ResourceManager.GetString("CameraTrackingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le bitmap de couleur doit être initialisé.
        /// </summary>
        internal static string ColorBitmapNull {
            get {
                return ResourceManager.GetString("ColorBitmapNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez d&apos;abord un appareil, puis redémarrez le programme!.
        /// </summary>
        internal static string ConnectDeviceFirst {
            get {
                return ResourceManager.GetString("ConnectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fps: {0:0.00}.
        /// </summary>
        internal static string Fps {
            get {
                return ResourceManager.GetString("Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maillage invalide.
        /// </summary>
        internal static string InvalidMeshArgument {
            get {
                return ResourceManager.GetString("InvalidMeshArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun périphérique DirectX11 détecté ou index de périphérique non valide - Kinect Fusion nécessite un périphérique DirectX11 pour la reconstruction basée sur GPU..
        /// </summary>
        internal static string NoDirectX11CompatibleDeviceOrInvalidDeviceIndex {
            get {
                return ResourceManager.GetString("NoDirectX11CompatibleDeviceOrInvalidDeviceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune Kinect trouvée!.
        /// </summary>
        internal static string NoKinectReady {
            get {
                return ResourceManager.GetString("NoKinectReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reconstruction a été réinitialisée..
        /// </summary>
        internal static string ResetReconstruction {
            get {
                return ResourceManager.GetString("ResetReconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le suivi a échoué, réinitialistion automatique du volume..
        /// </summary>
        internal static string ResetVolume {
            get {
                return ResourceManager.GetString("ResetVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La surface ombrée doit être initialisée.
        /// </summary>
        internal static string ShadedSurfaceNull {
            get {
                return ResourceManager.GetString("ShadedSurfaceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le volume doit être initialisé.
        /// </summary>
        internal static string VolumeNull {
            get {
                return ResourceManager.GetString("VolumeNull", resourceCulture);
            }
        }
    }
}
